name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: 0 0 * * 1-5

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - run: ./mvnw -B package

      - run: ./gradlew build

      - name: Enable auto merge for Dependabot PRs
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          gh pr review --approve "${{ github.event.pull_request.html_url }}"
          gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
