name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: 0 0 * * 1-5

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - run: ./mvnw -B package

      - run: ./gradlew build
