name: Verify

on:
  push:
    branches:
      - main
      - solutions
  schedule:
    - cron: 0 0 * * 1-5

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: build with Maven
        run: ./mvnw -B package
      - name: build with Gradle
        run: ./gradlew build
